# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.
# Docs: https://gohugo.io/content-management/menus/#define-in-site-configuration

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: Speakers
    url: /#speakers
    weight: 30
  - name: Program
    url: /#program
  - name: Location
    url: /#location  

footer:
  - identifier: home
    name: Home
    weight: 1
  - parent: home
    name: Home
    url: /
    weight: 1
  - identifier: about
    name: About
    weight: 2
  - parent: about
    name: About
    url: /#about
    weight: 2
  - identifier: speakers
    name: Speakers
    weight: 3
  - parent: speakers
    name: Speakers
    url: /#speakers
  - identifier: program
    name: Program
    weight: 3
  - parent: program
    name: Program
    url: /#program
    weight: 4
  - identifier: location
    name: Location
    weight: 4
  - parent: location
    name: Location
    url: /#location
  - identifier: register
    name: Register
    weight: 5
  - parent: register
    name: Register
    url: https://forms.office.com/r/MSd8cCWwqA
    weight: 5
